openapi: 3.1.0
info:
  version: 1.0.0
  title: OpenAPI Documentation
  description: This is the OpenAPI documentation for the API.
  termsOfService: http://swagger.io/terms/
  contact:
    name: Dipesh Hazesoft
    url: https://www.hazesoft.com
    email: dipesh@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:8080
    description: Development server
  - url: http://localhost:8000
    description: Production server
security: 
  -  jwt_auth: []
paths:
  /products:
    $ref: 'paths\products\products.yaml'
  /product/{id}:
    $ref: 'paths\products\product_{id}.yaml'
components:
  securitySchemes:
    jwt_auth:
        type: http
        scheme: bearer
        description: JWT Authorization header using the Bearer scheme.
        bearerFormat: JWT
        
